packages:
  - apps/*
  - packages/*

catalog:
  "@clerk/clerk-expo": 2.19.36
  "@clerk/nextjs": 6.39.3
  "@easypost/api": 8.9.0
  "@next/bundle-analyzer": 16.2.10
  "@prisma/client": 6.19.2
  "@react-navigation/native": 7.3.13
  "@react-navigation/native-stack": 7.18.5
  "@sentry/nextjs": 10.39.0
  "@stripe/connect-js": 3.3.34
  "@stripe/react-connect-js": 3.3.33
  "@stripe/react-stripe-js": 5.6.0
  "@stripe/stripe-js": 8.8.0
  "@stripe/stripe-react-native": 0.58.0
  "@tamagui/animations-css": 1.144.4
  "@tamagui/animations-react-native": 1.144.4
  "@tamagui/babel-plugin": 1.144.4
  "@tamagui/card": 1.144.4
  "@tamagui/cli": 1.144.4
  "@tamagui/config": 1.144.4
  "@tamagui/core": 1.144.4
  "@tamagui/font-inter": 1.144.4
  "@tamagui/lucide-icons": 1.144.4
  "@tamagui/next-plugin": 1.144.4
  "@tamagui/next-theme": 1.144.4
  "@tamagui/polyfill-dev": 1.144.4
  "@tamagui/popover": 1.144.4
  "@tamagui/portal": 1.144.4
  "@tamagui/sheet": 1.144.4
  "@tamagui/shorthands": 1.144.4
  "@tamagui/slider": 1.144.4
  "@tamagui/switch": 1.144.4
  "@tamagui/themes": 1.144.4
  "@tamagui/toast": 1.144.4
  "@types/canvas-confetti": 1.9.0
  "@types/node": 22.20.1
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  "@vercel/analytics": 1.6.1
  "@vercel/speed-insights": 1.3.1
  canvas-confetti: 1.9.4
  cloudinary: 2.10.0
  date-fns: 4.4.0
  embla-carousel: 8.6.0
  embla-carousel-autoplay: 8.6.0
  embla-carousel-react: 8.6.0
  eslint: 9.39.5
  eslint-config-expo: 10.0.0
  eslint-config-next: 16.2.10
  expo: 54.0.36
  expo-auth-session: 7.0.11
  expo-font: 14.0.12
  expo-image-picker: 17.0.11
  expo-notifications: 0.32.17
  expo-secure-store: 15.0.8
  expo-splash-screen: 31.0.13
  expo-status-bar: 3.0.9
  expo-updates: 29.0.19
  expo-web-browser: 15.0.11
  framer-motion: 12.42.2
  jose: 6.2.4
  lucide-react: 0.577.0
  next: 16.2.10
  next-cloudinary: 6.17.5
  next-seo: 7.2.0
  next-sitemap: 4.2.3
  nuka-carousel: 8.2.0
  prisma: 6.19.2
  react: 19.2.4
  react-dom: 19.2.4
  react-image-crop: 11.1.2
  react-native: 0.86.0
  react-native-reanimated: 4.5.3
  react-native-safe-area-context: 5.8.0
  react-native-screens: 4.26.2
  react-native-svg: 15.15.5
  react-native-web: 0.21.2
  react-native-webview: 13.17.0
  react-native-worklets: 0.11.1
  resend: 6.18.0
  solito: 5.0.0
  stripe: 19.3.1
  svix: 1.85.0
  tamagui: 1.144.4
  tsx: 4.23.1
  typescript: 5.9.3
  uuid: 13.0.2
